"""base_type (colonias orbitales SDD 37 v2)

Revision ID: 00c1ee69af3f
Revises: 9b8c21f67138
Create Date: 2026-06-25 03:08:56.717258
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00c1ee69af3f'
down_revision: str | None = '9b8c21f67138'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bases', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('base_type', sa.String(length=20),
                      server_default='surface', nullable=False)
        )
    # (omito el "rename" del unique de intel_reports: desajuste de nombre preexistente, cosmético)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bases', schema=None) as batch_op:
        batch_op.drop_column('base_type')

    # ### end Alembic commands ###
