"""resource_stocks por planeta (SDD 42 Fase 2)

Revision ID: 19328e7f3a26
Revises: b0906074dc0b
Create Date: 2026-06-25 05:49:52.854383
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19328e7f3a26'
down_revision: str | None = 'b0906074dc0b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # SDD 42 Fase 2: el stock pasa a ser POR PLANETA.
    with op.batch_alter_table('resource_stocks', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('planet_key', sa.String(length=50), server_default='', nullable=False)
        )
    # Backfill: el stock existente vive en el MUNDO NATAL del jugador (backward-compatible).
    op.execute(
        "UPDATE resource_stocks SET planet_key = COALESCE("
        "(SELECT planet_key FROM players WHERE players.id = resource_stocks.player_id), '') "
        "WHERE planet_key = '' OR planet_key IS NULL"
    )
    with op.batch_alter_table('resource_stocks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_player_mineral'), type_='unique')
        batch_op.create_unique_constraint(
            'uq_player_mineral_planet', ['player_id', 'mineral_key', 'planet_key']
        )
    # (omito el "rename" cosmético del unique de intel_reports, como en migraciones previas)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_stocks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_player_mineral_planet', type_='unique')
        batch_op.create_unique_constraint(
            batch_op.f('uq_player_mineral'), ['player_id', 'mineral_key']
        )
        batch_op.drop_column('planet_key')
