"""initial schema

Revision ID: 1aaf8f074f0b
Revises: 
Create Date: 2026-06-19 21:07:44.343493
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aaf8f074f0b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('galaxy_key', sa.String(length=50), nullable=True),
    sa.Column('planet_key', sa.String(length=50), nullable=True),
    sa.Column('race_key', sa.String(length=50), nullable=True),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('energy_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_username'), ['username'], unique=True)

    op.create_table('active_boons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('source_moon', sa.String(length=50), nullable=False),
    sa.Column('effect', sa.String(length=30), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active_boons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_boons_player_id'), ['player_id'], unique=False)

    op.create_table('bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('planet_key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bases_player_id'), ['player_id'], unique=False)

    op.create_table('combat_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attacker_id', sa.Integer(), nullable=False),
    sa.Column('defender_id', sa.Integer(), nullable=False),
    sa.Column('target_base_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attacker_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defender_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('combat_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_combat_logs_attacker_id'), ['attacker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_combat_logs_defender_id'), ['defender_id'], unique=False)

    op.create_table('expedition_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('moon_key', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completes_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expedition_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expedition_orders_player_id'), ['player_id'], unique=False)

    op.create_table('resource_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('mineral_key', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'mineral_key', name='uq_player_mineral')
    )
    with op.batch_alter_table('resource_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_stocks_player_id'), ['player_id'], unique=False)

    op.create_table('unit_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('unit_key', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'unit_key', name='uq_player_unit')
    )
    with op.batch_alter_table('unit_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_stocks_player_id'), ['player_id'], unique=False)

    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_id', sa.Integer(), nullable=False),
    sa.Column('building_key', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('production_mineral', sa.String(length=50), nullable=True),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completes_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buildings_base_id'), ['base_id'], unique=False)

    op.create_table('training_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_id', sa.Integer(), nullable=False),
    sa.Column('unit_key', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completes_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['bases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_orders_base_id'), ['base_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_orders_base_id'))

    op.drop_table('training_orders')
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buildings_base_id'))

    op.drop_table('buildings')
    with op.batch_alter_table('unit_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_stocks_player_id'))

    op.drop_table('unit_stocks')
    with op.batch_alter_table('resource_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_stocks_player_id'))

    op.drop_table('resource_stocks')
    with op.batch_alter_table('expedition_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expedition_orders_player_id'))

    op.drop_table('expedition_orders')
    with op.batch_alter_table('combat_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_combat_logs_defender_id'))
        batch_op.drop_index(batch_op.f('ix_combat_logs_attacker_id'))

    op.drop_table('combat_logs')
    with op.batch_alter_table('bases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bases_player_id'))

    op.drop_table('bases')
    with op.batch_alter_table('active_boons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_boons_player_id'))

    op.drop_table('active_boons')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_username'))

    op.drop_table('players')
    # ### end Alembic commands ###
