"""transport_missions (SDD 42 Fase 2)

Revision ID: 216679293f70
Revises: 19328e7f3a26
Create Date: 2026-06-25 06:11:42.744068
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216679293f70'
down_revision: str | None = '19328e7f3a26'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('from_planet', sa.String(length=50), nullable=False),
    sa.Column('to_planet', sa.String(length=50), nullable=False),
    sa.Column('cargo', sa.Text(), nullable=False),
    sa.Column('ships', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrives_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transport_missions', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_transport_missions_player_id'), ['player_id'], unique=False
        )
    # (omito el "rename" cosmético del unique de intel_reports, como en migraciones previas)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('transport_missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transport_missions_player_id'))

    op.drop_table('transport_missions')
    # ### end Alembic commands ###
