"""advisor: assistant hacks + advisor_messages

Revision ID: 2acd1ba3e8d9
Revises: 3e99d4fe9840
Create Date: 2026-06-22 04:04:07.645736
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2acd1ba3e8d9'
down_revision: str | None = '3e99d4fe9840'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisor_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisor_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advisor_messages_player_id'), ['player_id'], unique=False)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant_hacks_used', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('assistant_hacks_reset_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('assistant_hacks_reset_at')
        batch_op.drop_column('assistant_hacks_used')

    with op.batch_alter_table('advisor_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisor_messages_player_id'))

    op.drop_table('advisor_messages')
    # ### end Alembic commands ###
