"""game_events journal (SDD 38)

Revision ID: 3998d4757093
Revises: 43d73670dc4b
Create Date: 2026-06-24 19:41:01.805645
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3998d4757093'
down_revision: str | None = '43d73670dc4b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_events_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_events_type'), ['type'], unique=False)

    # NB: el autogenerate también detecta un "rename" del unique de intel_reports
    # (uq_intel_observer_target ↔ uq_intel_obs_target): es un desajuste de nombre preexistente,
    # cosmético; NO se toca acá para no romper en prod si el nombre real difiere.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_events_type'))
        batch_op.drop_index(batch_op.f('ix_game_events_player_id'))
        batch_op.drop_index(batch_op.f('ix_game_events_created_at'))

    op.drop_table('game_events')
    # ### end Alembic commands ###
