"""alliance chat messages

Revision ID: 3e99d4fe9840
Revises: c41714fd55b0
Create Date: 2026-06-21 11:05:28.055426
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e99d4fe9840'
down_revision: str | None = 'c41714fd55b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alliance_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alliance_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alliance_id'], ['alliances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alliance_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alliance_messages_alliance_id'), ['alliance_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alliance_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alliance_messages_alliance_id'))

    op.drop_table('alliance_messages')
    # ### end Alembic commands ###
