"""espionage: spy_missions + intel_reports (SDD 35)

Revision ID: 43d73670dc4b
Revises: 916dc21e5905
Create Date: 2026-06-24 15:27:10.485824
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d73670dc4b'
down_revision: str | None = '916dc21e5905'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intel_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observer_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('depth', sa.Float(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['observer_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observer_id', 'target_id', name='uq_intel_observer_target')
    )
    with op.batch_alter_table('intel_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intel_reports_observer_id'), ['observer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intel_reports_target_id'), ['target_id'], unique=False)

    op.create_table('spy_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observer_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_base_id', sa.Integer(), nullable=False),
    sa.Column('force', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrives_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returns_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['observer_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spy_missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spy_missions_observer_id'), ['observer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spy_missions_target_id'), ['target_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spy_missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spy_missions_target_id'))
        batch_op.drop_index(batch_op.f('ix_spy_missions_observer_id'))

    op.drop_table('spy_missions')
    with op.batch_alter_table('intel_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intel_reports_target_id'))
        batch_op.drop_index(batch_op.f('ix_intel_reports_observer_id'))

    op.drop_table('intel_reports')
    # ### end Alembic commands ###
