"""player_samples (SDD 51 analytics)

Revision ID: 4e2f998dc2ef
Revises: 865940154e14
Create Date: 2026-06-28 05:23:51.399119
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e2f998dc2ef'
down_revision: str | None = '865940154e14'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('energy_max', sa.Float(), nullable=False),
    sa.Column('stock_total', sa.Float(), nullable=False),
    sa.Column('units_total', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('stocks_json', sa.Text(), nullable=False),
    sa.Column('units_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_samples_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_samples_player_id'), ['player_id'], unique=False)

    # (omito el "rename" cosmético del unique de intel_reports, como en migraciones previas)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_samples_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_samples_at'))

    op.drop_table('player_samples')
    # ### end Alembic commands ###
