"""add attack_missions

Revision ID: 5a8641677e36
Revises: 9ad9e76c118a
Create Date: 2026-06-19 22:18:55.409759
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a8641677e36'
down_revision: str | None = '9ad9e76c118a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attacker_id', sa.Integer(), nullable=False),
    sa.Column('defender_id', sa.Integer(), nullable=False),
    sa.Column('target_base_id', sa.Integer(), nullable=False),
    sa.Column('force', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrives_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('returns_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attacker_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defender_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attack_missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attack_missions_attacker_id'), ['attacker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attack_missions_defender_id'), ['defender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attack_missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attack_missions_defender_id'))
        batch_op.drop_index(batch_op.f('ix_attack_missions_attacker_id'))

    op.drop_table('attack_missions')
    # ### end Alembic commands ###
