"""player_stats (SDD 12)

Revision ID: 68f1842a3469
Revises: cd692c8b7eae
Create Date: 2026-06-22 18:08:57.562184
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f1842a3469'
down_revision: str | None = 'cd692c8b7eae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('battles_won', sa.Integer(), server_default='0', nullable=False),
    sa.Column('battles_lost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('attacks_launched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('buildings_built', sa.Integer(), server_default='0', nullable=False),
    sa.Column('units_trained', sa.Integer(), server_default='0', nullable=False),
    sa.Column('research_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expeditions_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resources_mined', sa.Float(), server_default='0', nullable=False),
    sa.Column('resources_looted', sa.Float(), server_default='0', nullable=False),
    sa.Column('resources_lost', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    # ### end Alembic commands ###
