"""quantum_infections table (SDD 87)

Revision ID: 8587a5090248
Revises: d7ff71187c52
Create Date: 2026-07-08 17:03:11.297421
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8587a5090248'
down_revision: str | None = 'd7ff71187c52'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quantum_infections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defender_id', sa.Integer(), nullable=False),
    sa.Column('attacker_id', sa.Integer(), nullable=False),
    sa.Column('base_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('disarm', sa.String(length=20), nullable=True),
    sa.Column('leaking', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disarmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attacker_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defender_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quantum_infections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quantum_infections_attacker_id'), ['attacker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quantum_infections_base_id'), ['base_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quantum_infections_defender_id'), ['defender_id'], unique=False)
    # (drift de intel_reports omitido: `make migration` reescribe un uq preexistente, no es del SDD 87)
    # ### end Alembic commands ###


def downgrade() -> None:
    with op.batch_alter_table('quantum_infections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quantum_infections_defender_id'))
        batch_op.drop_index(batch_op.f('ix_quantum_infections_base_id'))
        batch_op.drop_index(batch_op.f('ix_quantum_infections_attacker_id'))

    op.drop_table('quantum_infections')
    # ### end Alembic commands ###
