"""strike_missions + drone_squadrons (SDD 49/50)

Revision ID: 865940154e14
Revises: 1bf3ad4fdcc3
Create Date: 2026-06-28 02:45:38.441313
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865940154e14'
down_revision: str | None = '1bf3ad4fdcc3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drone_squadrons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('factory_base_id', sa.Integer(), nullable=False),
    sa.Column('target_base_id', sa.Integer(), nullable=False),
    sa.Column('planet_key', sa.String(length=50), nullable=False),
    sa.Column('force', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('max_ticks', sa.Integer(), nullable=True),
    sa.Column('ticks_done', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_tick_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drone_squadrons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drone_squadrons_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drone_squadrons_target_id'), ['target_id'], unique=False)

    op.create_table('strike_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attacker_id', sa.Integer(), nullable=False),
    sa.Column('defender_id', sa.Integer(), nullable=False),
    sa.Column('launcher_base_id', sa.Integer(), nullable=False),
    sa.Column('target_base_id', sa.Integer(), nullable=False),
    sa.Column('force', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrives_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attacker_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defender_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strike_missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strike_missions_attacker_id'), ['attacker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strike_missions_defender_id'), ['defender_id'], unique=False)

    # (omito el "rename" cosmético del unique de intel_reports, como en migraciones previas)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strike_missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strike_missions_defender_id'))
        batch_op.drop_index(batch_op.f('ix_strike_missions_attacker_id'))

    op.drop_table('strike_missions')
    with op.batch_alter_table('drone_squadrons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drone_squadrons_target_id'))
        batch_op.drop_index(batch_op.f('ix_drone_squadrons_owner_id'))

    op.drop_table('drone_squadrons')
    # ### end Alembic commands ###
