"""seasons + hall_of_fame + protected_until (SDD 11)

Revision ID: 8cf01334bc5c
Revises: 131f87c961b5
Create Date: 2026-06-22 17:20:01.501960
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf01334bc5c'
down_revision: str | None = '131f87c961b5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seasons_seq'), ['seq'], unique=False)
        batch_op.create_index(batch_op.f('ix_seasons_status'), ['status'], unique=False)

    op.create_table('hall_of_fame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hall_of_fame', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hall_of_fame_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hall_of_fame_season_id'), ['season_id'], unique=False)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protected_until', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('protected_until')

    with op.batch_alter_table('hall_of_fame', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hall_of_fame_season_id'))
        batch_op.drop_index(batch_op.f('ix_hall_of_fame_player_id'))

    op.drop_table('hall_of_fame')
    with op.batch_alter_table('seasons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seasons_status'))
        batch_op.drop_index(batch_op.f('ix_seasons_seq'))

    op.drop_table('seasons')
    # ### end Alembic commands ###
