"""npc strategy fields (SDD 29)

Revision ID: 916dc21e5905
Revises: e2e8113bcd73
Create Date: 2026-06-24 11:56:48.952042
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916dc21e5905'
down_revision: str | None = 'e2e8113bcd73'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('npc_posture', sa.String(length=20), server_default='opportunist', nullable=False))
        batch_op.add_column(sa.Column('npc_target_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('npc_strategy', sa.Text(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('npc_strategy_updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('npc_strategy_updated_at')
        batch_op.drop_column('npc_strategy')
        batch_op.drop_column('npc_target_id')
        batch_op.drop_column('npc_posture')

    # ### end Alembic commands ###
