"""add npc_memory to players

Revision ID: 9ad9e76c118a
Revises: eab0bfa6406e
Create Date: 2026-06-19 21:55:33.282577
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ad9e76c118a'
down_revision: str | None = 'eab0bfa6406e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        # server_default so existing rows backfill to an empty memory list
        batch_op.add_column(
            sa.Column('npc_memory', sa.Text(), nullable=False, server_default='[]')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('npc_memory')

    # ### end Alembic commands ###
