"""world_events + event_grants (SDD 36)

Revision ID: 9b8c21f67138
Revises: 3998d4757093
Create Date: 2026-06-24 20:42:31.626209
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8c21f67138'
down_revision: str | None = '3998d4757093'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('effect', sa.String(length=30), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('world_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_world_events_ends_at'), ['ends_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_world_events_key'), ['key'], unique=False)

    op.create_table('event_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['world_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'event_id', name='uq_event_grant')
    )
    with op.batch_alter_table('event_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_grants_player_id'), ['player_id'], unique=False)

    # (omito el "rename" del unique de intel_reports: desajuste de nombre preexistente, cosmético)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_grants_player_id'))

    op.drop_table('event_grants')
    with op.batch_alter_table('world_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_world_events_key'))
        batch_op.drop_index(batch_op.f('ix_world_events_ends_at'))

    op.drop_table('world_events')
    # ### end Alembic commands ###
