"""meta_insights + game_events.version (SDD 41)

Revision ID: b0906074dc0b
Revises: b55f5253b1d7
Create Date: 2026-06-25 04:42:17.060114
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0906074dc0b'
down_revision: str | None = 'b55f5253b1d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_insights',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('sample_n', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('version', sa.String(length=20), server_default='dev', nullable=False)
        )
        batch_op.create_index(batch_op.f('ix_game_events_version'), ['version'], unique=False)
    # (omito el "rename" del unique de intel_reports: desajuste de nombre preexistente, cosmético)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_events_version'))
        batch_op.drop_column('version')

    op.drop_table('meta_insights')
    # ### end Alembic commands ###
