"""assist_energy daily counter (SDD 40)

Revision ID: b55f5253b1d7
Revises: 00c1ee69af3f
Create Date: 2026-06-25 04:08:19.056456
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b55f5253b1d7'
down_revision: str | None = '00c1ee69af3f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('assist_energy_used', sa.Integer(), server_default='0', nullable=False)
        )
        batch_op.add_column(
            sa.Column('assist_energy_reset_at', sa.DateTime(timezone=True), nullable=True)
        )
    # (omito el "rename" del unique de intel_reports: desajuste de nombre preexistente, cosmético)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('assist_energy_reset_at')
        batch_op.drop_column('assist_energy_used')

    # ### end Alembic commands ###
