"""add alliance type

Revision ID: c41714fd55b0
Revises: c94bcc334470
Create Date: 2026-06-20 17:13:13.467055
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41714fd55b0'
down_revision: str | None = 'c94bcc334470'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alliances', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('type', sa.String(length=30), nullable=False, server_default='full')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alliances', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
