"""add alliances

Revision ID: c94bcc334470
Revises: cd75a401c113
Create Date: 2026-06-20 16:16:26.868298
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94bcc334470'
down_revision: str | None = 'cd75a401c113'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alliances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('tag', sa.String(length=8), nullable=False),
    sa.Column('leader_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alliances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alliances_name'), ['name'], unique=True)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alliance_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_players_alliance_id'), ['alliance_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_players_alliance_id', 'alliances', ['alliance_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('fk_players_alliance_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_players_alliance_id'))
        batch_op.drop_column('alliance_id')

    with op.batch_alter_table('alliances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alliances_name'))

    op.drop_table('alliances')
    # ### end Alembic commands ###
