"""galaxy_instances + player.galaxy_instance_id (SDD 8)

Revision ID: cd692c8b7eae
Revises: 8cf01334bc5c
Create Date: 2026-06-22 17:51:19.198747
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd692c8b7eae'
down_revision: str | None = '8cf01334bc5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('galaxy_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_key', sa.String(length=50), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('player_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('galaxy_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_galaxy_instances_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_galaxy_instances_template_key'), ['template_key'], unique=False)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('galaxy_instance_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_players_galaxy_instance_id'), ['galaxy_instance_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_players_galaxy_instance', 'galaxy_instances',
            ['galaxy_instance_id'], ['id'], ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('fk_players_galaxy_instance', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_players_galaxy_instance_id'))
        batch_op.drop_column('galaxy_instance_id')

    with op.batch_alter_table('galaxy_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_galaxy_instances_template_key'))
        batch_op.drop_index(batch_op.f('ix_galaxy_instances_status'))

    op.drop_table('galaxy_instances')
    # ### end Alembic commands ###
