"""add research tables

Revision ID: cd75a401c113
Revises: b6811a7cc144
Create Date: 2026-06-20 16:07:08.237505
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd75a401c113'
down_revision: str | None = 'b6811a7cc144'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_techs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('tech_key', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'tech_key', name='uq_player_tech')
    )
    with op.batch_alter_table('player_techs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_techs_player_id'), ['player_id'], unique=False)

    op.create_table('research_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('tech_key', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completes_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_orders_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_orders_player_id'))

    op.drop_table('research_orders')
    with op.batch_alter_table('player_techs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_techs_player_id'))

    op.drop_table('player_techs')
    # ### end Alembic commands ###
