"""add is_npc to players

Revision ID: eab0bfa6406e
Revises: 1aaf8f074f0b
Create Date: 2026-06-19 21:23:48.380112
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab0bfa6406e'
down_revision: str | None = '1aaf8f074f0b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        # server_default so existing rows backfill to False (safe on populated tables)
        batch_op.add_column(
            sa.Column('is_npc', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('is_npc')

    # ### end Alembic commands ###
