"""market_prices hub (SDD 42 Fase 3)

Revision ID: f34d016beb6d
Revises: 216679293f70
Create Date: 2026-06-25 06:25:13.445797
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34d016beb6d'
down_revision: str | None = '216679293f70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('galaxy_key', sa.String(length=50), nullable=False),
    sa.Column('mineral_key', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('galaxy_key', 'mineral_key', name='uq_market_price')
    )
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_market_prices_galaxy_key'), ['galaxy_key'], unique=False
        )
    # (omito el "rename" cosmético del unique de intel_reports, como en migraciones previas)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_prices_galaxy_key'))

    op.drop_table('market_prices')
    # ### end Alembic commands ###
